2024-11-26 07:27:57 +0000 - dagster - DEBUG - dbt_seed_pipeline - b13435ba-7415-45d2-ac31-367c413db047 - 40236 - LOGS_CAPTURED - Started capturing logs in process (pid: 40236).
2024-11-26 07:27:57 +0000 - dagster - DEBUG - dbt_seed_pipeline - b13435ba-7415-45d2-ac31-367c413db047 - 40236 - run_dbt_seeds - STEP_START - Started execution of step "run_dbt_seeds".
2024-11-26 07:27:58 +0000 - dagster - ERROR - dbt_seed_pipeline - b13435ba-7415-45d2-ac31-367c413db047 - 40236 - run_dbt_seeds - STEP_FAILURE - Execution of step "run_dbt_seeds" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "run_dbt_seeds"::

TypeError: DbtCliResource.cli() missing 1 required positional argument: 'args'

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 482, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/app/gcp_dagster/dags/setup_seed.py", line 22, in run_dbt_seeds
    context.resources.dbt.cli(["run", "--select", "path:seeds"]).wait()

